name: Debricked Vulnerable Functionality for Java Maven
author: Debricked
description: todo
runs:
  using: docker
  image: docker://debricked/vulnerable-functionality:vulnerable-functionality-java-maven
branding:
  color: purple
  icon: filter
