name: Vulnerable Functionality Generic

on: [push]

jobs:
  vulnfunc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - run: mvn -B -f java/common package dependency:copy-dependencies -DoutputDirectory=java/common/dependencies -DskipTests
    - run: ls -RF java
    - run: ls -RF
    - uses: debricked/vulnerable-functionality/java@master
      with:
        path-to-compiled-files: 'java/common/target/classes/'
        path-to-library-files: 'java/common/dependencies'
